add workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,3 +8,13 @@ jobs:
         steps:
             - name: Say hello
               run: echo "Hello,World!"
+
+    echo-goodbye:
+        run-on: ubuntu-latest
+        steps:
+            - name: Failed step
+              run: |
+               echo "I will fail"
+               exit 1
+            - name: Say Goodbye
+              run: echo "Goodbye"
